version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
      MYSQL_DATABASE: task_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: ./api
    container_name: fastapi-api
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypass
      DB_NAME: task_db
    expose:
      - "8000"

  web:
    build: ./web
    container_name: flask-web
    depends_on:
      - api
    expose:
      - "5000"

  proxy:
    build: ./proxy
    container_name: nginx-proxy
    depends_on:
      - api
      - web
    ports:
      - "80:80"
    # NginxがFlask(5000)とFastAPI(8000)それぞれにリバースプロキシする

volumes:
  db_data:
