apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: simple-taskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: flask
        image: nukano0522/simple-taskapp-flask-web:v0.1.8-8-ga75b7e6 # {"$imagepolicy": "flux-system:simple-taskapp-web"}
        ports:
        - containerPort: 5000
        env:
        - name: PROXY_HOST
          value: "proxy-service" # Nginx Service名を指定
        - name: API_HOST
          value: "api-service" # FastAPI Service名を指定
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: simple-taskapp
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
