# ==========================
# PersistentVolume の定義
# ==========================
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: simple-taskapp
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/mysql

---
# ==========================
# PersistentVolumeClaim の定義
# ==========================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: simple-taskapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# ==========================
# Deployment の定義
# ==========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: simple-taskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpass"
        - name: MYSQL_USER
          value: "myuser"
        - name: MYSQL_PASSWORD
          value: "mypass"
        - name: MYSQL_DATABASE
          value: "task_db"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc

---
# ==========================
# Service の定義
# ==========================
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: simple-taskapp
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None
