apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: simple-taskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: fastapi
        image: nukano0522/simple-taskapp-fastapi:v0.1.8-8-ga75b7e6 # {"$imagepolicy": "flux-system:simple-taskapp-api"}
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "db-service"
        - name: DB_USER
          value: "myuser"
        - name: DB_PASSWORD
          value: "mypass"
        - name: DB_NAME
          value: "task_db"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: simple-taskapp
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
