---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: simple-taskapp-web
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: simple-taskapp-web
  policy:
    semver:
      range: '>=0.0.0'
