---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: simple-taskapp-web
  namespace: flux-system
spec:
  image: nukano0522/simple-taskapp-flask-web
  interval: 1m0s
