apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- image-repository-api.yaml
- image-repository-web.yaml
- image-policy-api.yaml
- image-policy-web.yaml
- image-automation.yaml
